version: "3"

tasks:
  build:
    cmds:
      - go build ./cmd/pawnserver

  test:
    cmds:
      - go test ./...

  lint:
    cmds:
      - golangci-lint run ./...

  security:
    cmds:
      - go tool govulncheck ./...

  check:
    cmds:
      - test -z "$(gofumpt -l .)"
      - go test ./...
      - CGO_ENABLED=1 go test -race -shuffle=on ./...
      - go vet ./...
      - golangci-lint run ./...
      - go tool govulncheck ./...
